### ISSUE TITLE
Not saving Neatline Features points in Omeka item

### ISSUE THREAD

**Issue by paulsmith01** [scholarslab/NeatlineFeatures#80] opened 2013-10-16 12:09 UTC
A fresh installation of Omeka 2.1.2, with Neatline 2.1.1 and NeatlineFeatures   2.0.1 installed and activated. When I create a new item in Omeka, add some basic metadata (title, description, date), and then try and add something to coverage. I select 'Map' (which is already being shown be default anyway?). I zoom in the view, select a point on the map, and select 'save view'. Nothing apparently happens at this point, so I carry on and save the item. No coverage data is shown in the preview, and if I go back and edit the item, the coverage field is as it was before I added any point data.

There's nothing in my server logs, but the Javascript console does report:

Warning: you have included the Google Maps API multiple times on this page. This may cause unexpected errors. main.js:42
Uncaught TypeError: Cannot read property 'element' of undefined featureswidget.js:233

when I first load up the item edit screen. Not sure if this has any bearing, but the fact that there is an error in some Neatline Features javascript which appears to relate to updating fields, might be symptomatic?

**Comment by tamielbr** [comment] 2013-12-10 11:30
Same problem here, same installation. I use it, but nothing gets saved. 
Using Firebug, I get this error:
"TypeError: this.nlfeatures is undefined ...ode:function(){var t,e,n,i,o,s;for(s=this.map.baseLayer.name,n=null,i=["osm","gp...""

**Comment by erochest** [comment] 2014-04-10 14:02
Thanks. This is a duplicate of #82. This should be fixed in 2.0.2 (ade0910032d0291f1a80bbd113979fc47ca6b3fc).

Please upgrade and let me know if the problem is still there.

**Closed as completed by erochest** 2014-04-10 14:02 UTC
