### ISSUE TITLE
Make it possible to pan the map in public item show views

### ISSUE THREAD

**Issue by davidmcclure** [scholarslab/NeatlineFeatures#40] opened 2012-02-17 14:33 UTC
In the public item show view, the map control defaults to a box selection tool that lets you drag out an area on the map. When I hit the page, thought, I wanted to be able to pan the map, not select features.

It could be useful to add a simple control that would let you toggle back and forth. I suspect, though, that in most cases people will want / expect to be able to pan, since that's the default pattern in Google Maps, etc.

**Comment by erochest** [comment] 2012-03-01 17:13
This is a duplicate of #35.

**Closed as completed by erochest** 2012-03-01 17:13 UTC
Labels: feature
